mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/",include("polls.urls")),
    path('__debug__',include('debug_toolbar.urls')),
]

polls/urls.py
from django.urls import path
from . import views

# the name parameter is used to build the url using the url tag in templates
# the 'name' value as called by the {% url %} template tag

# adding namespace to an application 
# so that similar url patterns in app names can be distinguished
app_name = "polls"

urlpatterns = [
    path( "", views.IndexView.as_view(), name="index" ),
    path( "<int:pk>/details", views.DetailsView.as_view(), name="qtn_details" ),
    path( "<int:question_id>/results/", views.ResultsView.as_view(), name="qtn_results" ),
    path( "<int:question_id>/vote/", views.vote, name="qtn_vote" ),
    
] 

polls/models.py
from datetime import datetime, timedelta
from django.db import models

from django.utils import timezone

from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    @admin.display(boolean=True, ordering="pub_date", description = "Published Recently?")
    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text


notes ="""

python manage shell

from interactive shell
using the API to play with the ORM 

# creating a query set manager
q = Question.objects.get(pk=1)

# calling on all the choices for this question
q.choice_set.all()

# creating 3 answers for this question
q.choice_set.create( choice_text = "I dont have one", votes = 0 )
q.choice_set.create( choice_text = "Girl is my name", votes = 0 )
c = q.choice_set.create( choice_text = "My name is a boy", votes = 0 )

# following relationships till what you want
Choice.objects.filter(question__pub_date__year=current_year)


# Let's delete one of the choices. Use delete() for that.
c = q.choice_set.filter(choice_text__startswith="Just hacking")
c.delete()

STUDY MORE ON ORM MANIPULATIONS


"""

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.utils import timezone
from polls.models import Choice, Question


# Create your views here.

class IndexView(generic.ListView):
    template_name="polls/index.html"
    context_object_name = "latest_questions_list"
    
    def get_queryset(self):
        # return last five published question 
        # Ignore all questions in the future from now
        return Question.objects.filter( pub_date__lte=timezone.now() ).order_by("-pub_date")[:5]

class DetailsView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"
    
    # # intercept the query so that user cant get future questions
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
    

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    pk_url_kwarg = "question_id"
    

# voting on a question
def vote(request, question_id):
    
    # get question to vote on
    question = get_object_or_404(Question, pk=question_id)
    
    try:
        selected_choice = question.choice_set.get( pk = request.POST['choice'] )
        
    except (KeyError, Choice.DoesNotExist):
        # return form to the user to try again
        
        return render (
            request,
            'polls/details.html',
            {
                "question": question,
                "error_message": "You didnt select a choice"
            }
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        
        return HttpResponseRedirect( 
                                    reverse( 
                                            "polls:qtn_results", 
                                            args=(question.id,)
                                            )
                                    )

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Django Polling App
        {% endblock %} 
    </title>
    {% block head %}{% endblock %}
</head>
<body>

    {% block content %}{% endblock %}
    
</body>
</html>

polls/templates/polls/details.html
{% extends "polls/base.html" %}


{% block content %}
<h1>
    {{ question.question_text }}
</h1>

{% for choice in question.choice_set.all  %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}

<form action="{% url "polls:qtn_vote" question.id %}" method="post" >
    
    {% csrf_token %}

    <fieldset>
    
        <legend>            
            <h1>{{ question.question_text }}</h1>
        </legend>
        
        {% if error_message %}
            <p>
                <strong> {{error_message}} </strong>
            </p>
        {% endif %}

        {% for choice in question.choice_set.all  %}
            
            <input 
                type="radio" 
                name="choice" 
                id="choice{{ forloop.counter }}"
                value="{{ choice.id }}"            
            >
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label><br>

        {% endfor %}

        <input type="submit" value="Vote">      
    
    </fieldset>

</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load static %}


{% block head %}
<link rel="stylesheet" href="{% static 'polls/styles.css' %}">
{% endblock %}

{% block title %} Polls Home {% endblock %}


{% block content %}
{% if latest_questions_list %}
    <ul>
        {% for question in latest_questions_list %}
        <li>
            <a href="{% url "polls:qtn_details" question.id %}">
                {{ question.question_text }}
            </a>
        </li>    
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:qtn_details' question.id %}">Vote again?</a>

{% endblock %}